language: node_js
node_js:
- 8
- node
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: update translations
      if: type == cron
      script: ./scripts/update-translations.sh
    - stage: npm release
      if: branch in (master, npm-publish) AND type != cron
      node_js: 8
      script: npm run build
      before_deploy:
      - VPKG=$($(npm bin)/json -f package.json version)
      - export VERSION=${VPKG/%?/}$(date +%Y%m%d%H%M%S)
      - npm --no-git-tag-version version $VERSION
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          all_branches: true
